version: "3"
services:
    ros2:
        image: adohaha/fun_ros:presentation
        volumes:
            - $PWD/jupyter_notebooks:/home/ubuntu/turtlebot3_ws/src/jupyter_notebooks
        ports: 
            - 6080:80
            - 8888:8888
        shm_size: '2gb'
        container_name: ros_fun
    
    
      
